### ISSUE TITLE
Meshing issue

### ISSUE THREAD

**Issue by KrisSaban** [WhiteCoreSim/WhiteCore-Dev#137]
I am unable to walk on or next to mesh items, I have a mesh bridge i made for opensim. in opensim i can walk on it just fine but in whitecore i cant if i fly above it and land on it i land 10 meters above the bridge, also with mesh houses the door ways no longer work but the did in opensim.

**Comment by emperorstarfinder** [comment]
Hi kris.

curious what error you get when you attempt this (if any) and what operating system your on.

**Comment by KrisSaban** [comment]
thats why i do not know whats wrong there are no errors on the grid server or region server. everything loads fine. 
OS: Windows server 2008 RT Data center (x64) 
.net: 3.5, 4.0, 4.5

whitecore version: both 0.9.2 and 0.9.3 dev.

grid login url: http://andromedagrid.com:9002/
Region: starting region

created account for anyone to login with to test.

user account
error user

password:
issues

**Comment by BogusCurry** [comment]
Hi Kris ;D Run your Grid with SQLite or Mysql ?

**Comment by KrisSaban** [comment]
mysql

**Comment by fly-man-** [comment]
I have seen some issues with mesh builds in the past. Especially when people are using the ODE physics engine. On the Bullet version we have at the moment it's less but still does the same after a period of time.

If your console outputs any errors or messages that might explain it, please make a Gist or a Pastebin so we can determine where exactly it goes wrong

**Comment by emperorstarfinder** [comment]
That is why I asked if there were any errors.  If you try to use bullet in one instance then export and import it into an instance using ODE you will have issues.  That is assuming kris is uploading a pre-made mesh and its not one they made on their own of course.

**Comment by QuillLittlefeather** [comment]
Jul 02 11:15:53 - [MESH]: exception decoding physical mesh: OpenMetaverse.Struct
uredData.OSDException: Binary LLSD parsing: Unknown type marker.
   at OpenMetaverse.StructuredData.OSDParser.ParseLLSDBinaryElement(Stream strea
m)
   at OpenMetaverse.StructuredData.OSDParser.DeserializeLLSDBinary(Stream stream
)
   at OpenMetaverse.StructuredData.OSDParser.DeserializeLLSDBinary(Byte[] binary
Data)
   at WhiteCore.Physics.Meshing.Meshmerizer.CreateMeshFromPrimMesher(String prim
Name, PrimitiveBaseShape primShape, Vector3 size, Single lod, UInt64 key) in c:\
Users\Littlefeather\Downloads\WhiteCore-Dev-master (1)\WhiteCore-Dev-master\Whit
eCore\Physics\Meshing\Meshmerizer.cs:line 290

**Comment by emperorstarfinder** [comment]
Is this happening with one mesh object you are uploading or multiple uploads? and which version of whitecore are you using?

**Comment by QuillLittlefeather** [comment]
this happens with all mesh and they were created in blender, I am using the latest dev 0.9.3.

**Comment by greythane** [comment]
Hi Quill, 
Can you get me a couple of examples that fail please so I can track through what is happening?
 (Dropbox, Gdrive, etc or email me if they are small enough

**Comment by QuillLittlefeather** [comment]
https://drive.google.com/open?id=0B577i6m2-GOsZXBNR0E5RmFQaDQ
https://drive.google.com/open?id=0B577i6m2-GOsT2xRR3JmckRXUmc

these are simple mesh items i made to test whitecore

**Comment by stormsonweathers** [comment]
I ran into a similar such as @QuillLittlefeather. For me it was related to this in both Meshmerizer.cs and RenderMaterials.cs:

https://github.com/WhiteCoreSim/WhiteCore-Dev/commit/223ce72816a4c4c789d86529f9f43b388aeced5f

and this change in both files:

- using (ZOutputStream zOut = new ZOutputStream(msSinkCompressed))
+ using (ZOutputStream zOut = new ZOutputStream(msSinkCompressed,1))

When I reverted back to the original on these lines, everything worked fine (for me anyways).

**Comment by greythane** [comment]
Correct, this is partially the problem but there are other corrections as well.
I will be pushing through a bunch of mesmeriser updates very soon.

**Comment by greythane** [comment]
Corrections pushed through and verified with supplied test objects from QuillLittleFeather (previously failed to load correctly)
Note: Some additional code has not yet been fully tested and verified

Please check and provide some feedback as to the functionality.

**Comment by QuillLittlefeather** [comment]
it work on ode but in buletsim i get stack overflow exception

**Comment by greythane** [comment]
Thanks Quill,
Yes, my checks usingBullet failed miserably.  I have already found some problems which may correct a few things.  Also, there are plans to get Bullet up to date as well.t

**Comment by fly-man-** [comment]
Bumping this issue to 0.9.4 as it's a Physics issue

**Comment by greythane** [comment]
Quill,
I have just implemented and pushed through a heap of updates for BulletSim that Fine did for us.  These also involve some changes in the meshing processing.
If you are able, could you grab the latest Dev (master) code and give Bulet a try again and see if the meshing issues you saw have changed in any way.
G

**Comment by QuillLittlefeather** [comment]
ok i will do that when i get home

**Comment by QuillLittlefeather** [comment]
I am still having issues with mesh unable to walk on them (can walk 10M ABOVE). and mesh with holes ex window  or doorway not working. could be my machine so when my new server arrives ill check again.

**Comment by greythane** [comment]
Quill, is this with bulletSim or ODE?

There is a known problem with ODE and mesh that gives the 'floating on air' problem.  
This is on my 'to do list' when I have time.

**Comment by QuillLittlefeather** [comment]
this is with bulletsim but going to try on fresh server

**Comment by fly-man-** [comment]
Moving this to 0.9.5

**Comment by fine77** [comment]
We have finsihed a new Version of Meshmerizer.
the roll out comes soon.
